DELETE FROM CLIENT;
DELETE FROM VEHICULE;
DELETE FROM IMPLICATION;
DELETE FROM CONTRAT;
DELETE FROM ACCIDENT;

ALTER TABLE CLIENT
DROP CONSTRAINTS PK_CLIENT;

ALTER TABLE CONTRAT
DROP CONSTRAINTS PK_CONTRAT;
ALTER TABLE CONTRAT
DROP CONSTRAINTS FK_CONTRAT_CONTRAT;

ALTER TABLE ACCIDENT
DROP CONSTRAINTS PK_ACCIDENT;

ALTER TABLE VEHICULE
DROP CONSTRAINTS PK_VEHICULE;
ALTER TABLE VEHICULE
DROP CONSTRAINTS FK_VEHICULE_CLIENT;
ALTER TABLE VEHICULE
DROP CONSTRAINTS FK_VEHICULE_CONTRAT;


ALTER TABLE IMPLICATION
DROP CONSTRAINTS PK_IMPLICATION;
ALTER TABLE IMPLICATION
DROP CONSTRAINTS FK_IMPLICATION_VEHICULE;



DROP TABLE CLIENT;
DROP TABLE VEHICULE;
DROP TABLE IMPLICATION;
DROP TABLE CONTRAT;
DROP TABLE ACCIDENT;