UN CLIENT PEUT SIGNER 0 A N CONTRAT
UN CONTRAT PEUT ETRE SIGNE PAR UN ET UN SEUL CLIENT
UN CLIENT POSSEDE 0 A N VEHICULE
UN VEHICULE APPARTIENT A 1 ET 1 SEUL VEHICULE
UN CONTRAT COUVRE AUCUN OU UN VEHICULE
UN VEHICULE EST COUVERT PAR UN ET UN SEUL CONTRAT
UN ACCIDENT IMPLIQUE 0 A N VEHICULE
UN VEHICULE PEUT ETRE IMPLIQUE DANS 0 A N ACCIDENT

INSERT INTO CLIENT(NUMCLIENT,NOM,ADRESSE)
()